### ISSUE TITLE
Can't Add Collectors During Setup

### ISSUE THREAD

**Issue by Spinkelben** [PrometheusClientNet/Prometheus.Client.AspNetCore#11]
With the change to use DI for injecting the ICollectorRegistry the `CollectorRegistryInstance` property of `PrometheusOptions` becomes useless. We used to configure our metrics like this.

```C#
app.UsePrometheusServer(prometheusOptions =>
{
    prometheusOptions.CollectorRegistryInstance.Add(new MySystemMetricCollector());
});
```

This no longer works. The property is null. If I create a new CollectorRegistry in this method it is ignored. So I would suggest you set it before invoking the setup function.

**Comment by Spinkelben** [comment]
Hmm, maybe I was too fast. I didn't fully understand the meaning of the  `??=` operator of this code:

```
options.CollectorRegistryInstance
                    ??= (ICollectorRegistry)app.ApplicationServices.GetService(typeof(ICollectorRegistry))
                    ?? Metrics.DefaultCollectorRegistry;
```

**Comment by Spinkelben** [comment]
Ah, I found the real issue. I guess I was partially correct. We use DI to inject a `IMetricFactory`. That includes a `ICollectorRegistry` instance. Unless we use the same `ICollectorRegistry` instance in the setup method, it has no effect. This code would fix it. 

```C#
app.UsePrometheusServer(x =>
{
    x.CollectorRegistryInstance = app.ApplicationServices.GetService<ICollectorRegistry>();
    x.CollectorRegistryInstance.Add(new MySystemMetricCollector());
});
```

However it is a bit stupid. It would be better, if we got the `ICollectorRegistry` instance from the `PrometheusOptions` object, when it is already registered in the DI container.

**Comment by sanych-sun** [comment]
Hi @Spinkelben!

Sorry for the late response. If you are using [DI integration library](https://github.com/PrometheusClientNet/Prometheus.Client.DependencyInjection) - the answer is simple: just remove the CollectorRegistryInstance property from options and it will be resolved from DI.

Currently we are using the following order:
1) use collector registry from options
2) try to resolve it from DI
3) use static instance (as a fallback for backward compatibility).

Please let me know if this works for you or do we need some additional help/changes?
